version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:eu-west-3:481160876852:task-definition/aws-hello-world-rest-api:3"
        LoadBalancerInfo:
          ContainerName: "hello-world-container"
          ContainerPort: "80"
        PlatformVersion: "LATEST"